server:
  port: 8080
spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:postgresql://library-app-backend-database.cfnj7zlyuktd.ap-northeast-2.rds.amazonaws.com:5432/library
    username: postgres
    password: pnu201724425
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddlAuto: validate



logging.level:
  org.hibernate:
    SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE


