spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddlAuto: create



logging.level:
  org.hibernate:
    SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE


