### 회원가입
POST {{user-api}}/member/signup
Content-Type: application/json

{
  "username": "김민종",
  "userId": "dummyId",
  "password": "dummyPassword",
  "birthday": "1998-12-11",
  "email": "koust6u@pusan.ac.kr"
}

### 로그인
POST {{user-api}}/member/login
Content-Type: application/json

{
  "userId": "dummyId",
  "password": "dummyPassword"
}


### 입금
POST {{user-api}}/account/deposit
Content-Type: application/json

{
  "credit": 100
}


### 잔액 조회
GET {{user-api}}/account
Content-Type: application/json
